# app.py
"""
Streamlit UI for the Jesse Livermore Mentor Bot.

Tab 1: RAG chatbot (Part 1)
Tab 2: Strategy backtest (Part 2)
"""

import streamlit as st
from datetime import date
from src.rag_chatbot import LivermoreRAGChatbot
from src.strategy import run_livermore_strategy


# ---------- CACHED BACKEND -----------

@st.cache_resource
def get_chatbot() -> LivermoreRAGChatbot:
    """
    Create and cache a single instance of the RAG chatbot backend.

    This ensures that the heavy FLAN-T5 model and embeddings are loaded
    only once, even when Streamlit reruns the script on every interaction.
    """
    bot = LivermoreRAGChatbot(excel_path="data/Team Livermore.xlsx")
    return bot


# ---------- PAGE CONFIG -----------

st.set_page_config(
    page_title="Jesse Livermore Mentor Bot",
    page_icon="📈",
    layout="wide",
)

st.title("Jesse Livermore Mentor Bot")
st.caption(
    "GenAI + RAG chatbot trained on curated Q&A about Jesse Livermore's life, "
    "strategy, timing, risk management, adaptability, and psychology."
)

# ---------- TABS -----------

tab_chat, tab_backtest = st.tabs(["💬 Chat with Jesse", "📈 Backtest Strategy"])


# ==============================
# TAB 1: CHAT WITH JESSE (PART 1)
# ==============================

with tab_chat:
    st.subheader("Chat with Jesse")

    st.write(
        "Ask questions about Jesse Livermore's trading philosophy, psychology, risk "
        "management, and more. The bot uses a Retrieval-Augmented Generation (RAG) "
        "pipeline built on your custom Q&A dataset."
    )

    # --- Initialize session state for chat history ---
    if "chat_messages" not in st.session_state:
        # each message: {"role": "user" | "assistant", "content": str, "sources": Optional[list]}
        st.session_state.chat_messages = []

    bot = get_chatbot()

    # --- 1) Render full chat history (older at top, newer at bottom) ---
    for msg in st.session_state.chat_messages:
        if msg["role"] == "user":
            with st.chat_message("user"):
                st.markdown(msg["content"])
        else:
            with st.chat_message("assistant"):
                st.markdown(msg["content"])
                sources = msg.get("sources") or []
                if sources:
                    with st.expander("Show sources used"):
                        for i, s in enumerate(sources, start=1):
                            st.markdown(
                                f"**{i}. [{s['label']}]** {s['question']}\n\n"
                                f"*Answer snippet:* {s['answer'][:200]}..."
                            )

    # --- 2) Chat input at the bottom of the page ---
    user_input = st.chat_input("Ask Jesse a question...")

    if user_input:
        # Add user message
        st.session_state.chat_messages.append(
            {"role": "user", "content": user_input}
        )

        # Compute answer (no immediate rendering)
        with st.spinner("Thinking like Jesse Livermore..."):
            answer, sources = bot.answer_question(user_input, k=3)

        # Add assistant message
        st.session_state.chat_messages.append(
            {"role": "assistant", "content": answer, "sources": sources}
        )

        # Force rerun so new messages appear in the history above, input stays at bottom
        st.rerun()

    # Optional note at the very bottom
    st.markdown(
        "<small>Note: Answers are generated by FLAN-T5 using retrieved Q&A "
        "about Jesse Livermore. The bot may sometimes paraphrase or condense "
        "the original answers.</small>",
        unsafe_allow_html=True,
    )

# ==============================
# TAB 2: BACKTEST STRATEGY 
# ==============================

with tab_backtest:
    st.subheader("Backtest Livermore's Breakout Strategy")

    st.write(
        "Backtest a Jesse Livermore-style breakout strategy on a selected stock. "
        "The strategy uses breakout above N-day highs combined with 50/200-day "
        "moving averages"
    )

    # -------- INPUTS (Hybrid UI: defaults but editable) --------
    col1, col2, col3 = st.columns(3)

    with col1:
        symbol = st.text_input("Stock symbol", value="AAPL")

    with col2:
        start_date = st.date_input(
            "Start date",
            value=date(2019, 1, 1),
        )

    with col3:
        end_date = st.date_input(
            "End date",
            value=date(2024, 12, 31),
        )

    st.markdown("#### Strategy Parameters")

    col4, col5, col6 = st.columns(3)

    with col4:
        breakout_window = st.number_input(
            "Breakout window (days)",
            min_value=5,
            max_value=60,
            value=20,
            step=5,
            help="Window for N-day high/low breakout (e.g., 20-day high/low).",
        )

    with col5:
        sma_short = st.number_input(
            "Short SMA (days)",
            min_value=10,
            max_value=100,
            value=50,
            step=5,
            help="Short-term trend filter (e.g., 50-day moving average).",
        )

    with col6:
        sma_long = st.number_input(
            "Long SMA (days)",
            min_value=50,
            max_value=300,
            value=200,
            step=10,
            help="Long-term trend filter (e.g., 200-day moving average).",
        )

    st.markdown("---")

    run_button = st.button("Run Backtest")

    if run_button:
        if not symbol.strip():
            st.error("Please enter a valid stock symbol.")
        elif start_date >= end_date:
            st.error("Start date must be before end date.")
        else:
            try:
                with st.spinner("Running Livermore breakout strategy..."):
                    res = run_livermore_strategy(
                        symbol=symbol.strip().upper(),
                        start_date=start_date,
                        end_date=end_date,
                        breakout_window=int(breakout_window),
                        sma_short=int(sma_short),
                        sma_long=int(sma_long),
                    )

                df = res.data
                summary = res.summary

                # -------- SUMMARY METRICS --------
                st.markdown("### Summary Results")

                m1, m2, m3 = st.columns(3)
                with m1:
                    st.metric(
                        "Total Trading Days",
                        f"{int(summary['total_days'])}",
                    )
                with m2:
                    st.metric(
                        "Buy & Hold Agg. Return",
                        f"{summary['buy_and_hold_agg_return']:.2%}",
                    )
                with m3:
                    st.metric(
                        "Strategy Agg. Return",
                        f"{summary['strategy_agg_return']:.2%}",
                    )

                # -------- CUMULATIVE RETURN CHART --------
                st.markdown("### Cumulative Returns (Agg. / cumsum)")

                chart_df = df[["BH_CumReturn", "Strategy_CumReturn"]].copy()
                chart_df.columns = ["Buy & Hold", "Livermore Strategy"]

                st.line_chart(chart_df)

                # -------- DATA PREVIEW --------
                st.markdown("### Recent Signals (last 5 rows)")
                cols_to_show = [
                    "Close",
                    f"{res.sma_short}MA",
                    f"{res.sma_long}MA",
                    f"{res.breakout_window}High",
                    f"{res.breakout_window}Low",
                    "Position",
                    "Buy-and-Hold Return",
                    "Strategy Return",
                    "BH_CumReturn",
                    "Strategy_CumReturn",
                ]
                st.dataframe(df[cols_to_show].tail(5))

                with st.expander("Show full backtest data"):
                    st.dataframe(df[cols_to_show])

            except Exception as e:
                st.error(f"Error while running backtest: {e}")